name: Calculate DevOps Metrics

on:
  push:

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    name: Checking the dora metrics
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DevOps Metrics from GitHub
        uses: stenjo/devops-metrics-action@v1.3.0
        id: dora
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
